server:
  port: 8084
  
spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/hotel/**
        - id: RATING-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/rating/**

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
      preferIpAddress: true
      
      
##  Okta configuration for api gateway
#okta:
#  oauth2:
#    issuer: https://dev-69865602.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oaj12mqz8zIuJ6gt5d7
#    client-secret: DoB1n1F01_-Z863xSxaKaLVgTI8ve9EL8ui6CBkJuyWVe9WlXS8moI82k2oofqTC
#    scopes: openid, profile, email, offline_access