server:
 port: 8081
 
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/microservices
   username: user1
   password: user@123
   driver-class-name: com.mysql.cj.jdbc.Driver
  application:
        name: USER-SERVICES
   
  jpa:
   hibernate: 
     ddl-auto: update
   show-sql: true
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect
#  config:
#   import: configserver:http://localhost:8085  
     
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
      preferIpAddress: true